### ISSUE TITLE
Server ticking issue with World Generation Manager

### ISSUE THREAD

**Issue by ppappila** [Electrical-Age/ElectricalAge#106]
I installed for test purposes Nei, codechickencore,World Generation Manager and your mod on a server. Nothing else was installed. 
the following error was produced
---- Minecraft Crash Report ----
// Why did you do that?

Time: 16/08/14 8:57 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:318)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
    at java.lang.Class.getMethod0(Class.java:2937)
    at java.lang.Class.getMethod0(Class.java:2947)
    at java.lang.Class.getMethod(Class.java:1771)
    at com.creativemd.generationmanager.GenerationDummyContainer.getName(GenerationDummyContainer.java:174)
    at com.creativemd.generationmanager.GenerationDummyContainer.onAdd(GenerationDummyContainer.java:194)
    at cpw.mods.fml.common.registry.GameRegistry.registerWorldGenerator(GameRegistry.java:79)
    at mods.eln.ore.OreItem.addDescriptor(OreItem.java:34)
    at mods.eln.Eln.registerOre(Eln.java:3049)
    at mods.eln.Eln.load(Eln.java:619)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IIconRegister
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 43 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at cpw.mods.fml.common.asm.transformers.TerminalTransformer.transform(TerminalTransformer.java:14)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
    ... 45 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.13.0-32-generic
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1499120088 bytes (1429 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
    JVM Flags: 2 total; -Xmx2048M -Xms2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 11 mods loaded, 11 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.25.1207} [Forge Mod Loader](forge-1.7.10-10.13.0.1207-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.0.1207} [Minecraft Forge](forge-1.7.10-10.13.0.1207-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.3.23} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.3.49} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.49-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    generationmanager{0.3.6} [Generation Manager Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Eln{37} [Electrical Age](ElectricalAge_BETA-1.9_r37.jar) Unloaded->Constructed->Pre-initialized->Errored
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.296} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.296} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.296} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Dolu1990** [comment]
Hi, Thanks for issue. i fix that, come in next update :)

**Comment by Dolu1990** [comment]
Oky i think it's ok now, but i don't have successfuly reproduct the bug, could you give me feed back if all is all right when r38 is out ?
