### ISSUE TITLE
Piping Lava bucket into the heat furnace slot 2

### ISSUE THREAD

**Issue by tomevoll** [Electrical-Age/ElectricalAge#129]
Piping a bucket of lava in to slot 2 will cause a crash.
I assume we are not suppose to pipe into that slot, however,  isItemValidForSlot returns true.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/10/14 10:30 AM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.item.ItemBucket cannot be cast to mods.eln.generic.GenericItemUsingDamage
    at mods.eln.transparentnode.heatfurnace.HeatFurnaceInventoryProcess.process(HeatFurnaceInventoryProcess.java:38)
    at mods.eln.sim.Simulator.tick(Simulator.java:499)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_582_Simulator_tick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by tomevoll** [comment]
Getting the unlocalizedname also dont work, returns null or a blank string. i have not checked properly what is going on with the name, but i failed to get the name using (itemstack getDisplayName, getunlocalizedname) (block getUnlocalizedname)

**Comment by JPitman97** [comment]
We will look into this don't see what is causing this though

**Comment by tomevoll** [comment]
i checked some more on the name, its not null, but they all return, tile.NodeBlock

**Comment by master801** [comment]
@ShadowWarrior979 
This is your problem.
https://github.com/Dolu1990/ElectricalAge/blob/1.7.2-MNA/mods/eln/transparentnode/electricalfurnace/ElectricalFurnaceProcess.java#L40

You're trying to cast a Class to an item that doesn't have the Class implemented anywhere in the code.

Example:
ItemStack stack; //This is a normal ItemStack that doesn't implemented IInterface.
((IInterface)stack).getItem(); //This will error out for sure.

**Comment by tomevoll** [comment]
ya a  try cache on that line eliminates the error,
I think preventing items to enter slot 2 would be a better solution. sorry for bad spelling.

maybe check if a item is instanceof ThermalIsolatorElement, when a class calls  isItemValidForSlot and if slot is 2 and its not a instance of  ThermalIsolatorElement return false?

**Comment by Dolu1990** [comment]
Hi,
I fix that in next release. Thanks for issue :)

**Comment by tomevoll** [comment]
any chance rf convertion and ic2 convertion ratio could be upped a bit? it seems incredible hard to get any usable amount of RF from it, even running full 5kw at 800v into a converter, with the new upgrades for speed and so on on TE, the draw is even larger, full 5kw seem to give around 100 RF/t ?

I would really like to use this mod for powering all other mods, not cause this is easier to set up, but its so much fun to play with :)

**Comment by tomevoll** [comment]
hmm this def, need a bump in convertion, im on 5kw output, me system draw 172 EU/t and ELN cant deliver that amount, MFSU being drained
![2014-09-12_11 06 36](https://cloud.githubusercontent.com/assets/8545471/4247608/5364cb82-3a5c-11e4-8e18-ce3c72c2f7b5.png)
![2014-09-12_11 07 00](https://cloud.githubusercontent.com/assets/8545471/4247610/61b68a0e-3a5c-11e4-9d71-5fa6d29b7c78.png)

**Comment by Dolu1990** [comment]
i have investigate, but i can't reproduct the bug. How do you have put the laval bucket in the slot ? because it's already protected. you use r40 ?
For energy convertion ratio. i can put in eln.cfg  the ratio.

**Comment by Dolu1990** [comment]
I have add into eln.cfg conversion ratio. (come in next release)
Using other electrical blocks mod is cool, they all have some part that are prety good. and Electrical age can't do all :)

**Comment by tomevoll** [comment]
im using 41, i will check again on isItemValid, im using Router Reborn (you can find it on curse, ill give you a link if you cant find it), it wouldnt insert an item there if isitemvalid return false, i will double check my code, it does not insert to other machines returning false, it was the heat furnace , not electrical furnace.

Thank you for adding it in cfg :)

**Comment by tomevoll** [comment]
k i checked and the heat furnace does return true.

![lava](https://cloud.githubusercontent.com/assets/8545471/4259282/09ff0b56-3aed-11e4-9c18-bc6ef6242910.png)

slots[0] is the item located in slot 0 in the router, it checks if the item is valid for the target slot before it will try and transfer it.

**Comment by tomevoll** [comment]
if you need the deobf version to use in debug i can give you a private link to it

**Comment by Dolu1990** [comment]
Enjoying with minecraft inventory implementation XD
So the minecraft inventory system has some duplicated and redondant function :
From IInventory there is isItemValidForSlot .
From ISidedInventory there is getAccessibleSlotsFromSide.
So getAccessibleSlotsFromSide is correctly implemented, but isItemValidForSlot is not.

For next update i will try to solve that automaticaly by the code itself :) thanks for issue.

minecraft 1.8 has re implement the inventory system ♥

**Comment by Dolu1990** [comment]
oky i have fix that,by the hugliest possible way XD
    @Override
    public boolean isItemValidForSlot(int i, ItemStack itemstack) {
        for(int idx = 0;idx < 6;idx++){
            int[] lol = getAccessibleSlotsFromSide(idx);
            for(int hohoho : lol){
                if(hohoho == i){
                    if(canInsertItem(i, itemstack, idx)) return true;
                }
            }
        }
        return false;
    }

Normaly all is ok now :)

**Comment by Dolu1990** [comment]
It's that no ? isItemValidForSlot ?

**Comment by tomevoll** [comment]
that should work :) i will test it :)

**Comment by tomevoll** [comment]
isItemValidForSlot in the tileentity yes. is this updated in git? i just reloaded the latest, but from what i see last change was a day ago, and it still returns true

**Comment by tomevoll** [comment]
the problem might be caninsertitem, if your tile is ISidedInventory this is called:
private boolean canPutStackIntoSlotSided(ISidedInventory target, int OUTPUT_SLOT, SIDE side, ItemStack stack)
    {
        if (stack != null)
        {
            if (stack.stackSize < stack.getMaxStackSize())
            {
                if (target.canInsertItem(OUTPUT_SLOT, slots[0], side.getCode()) && target.isItemValidForSlot(OUTPUT_SLOT, slots[0]))
                {
                    if (StackFitInStack(slots[0], stack))
                    {
                        return true;
                    }
                }
            }
        } else
        {
            if (target.canInsertItem(OUTPUT_SLOT, slots[0], side.getCode()) && target.isItemValidForSlot(OUTPUT_SLOT, slots[0]))
            {
                if (StackFitInStack(slots[0], stack))
                {
                    return true;
                }
            }
        }
        return false;
    }

i included image, the formating on code makes it almost unreadable :)
![code](https://cloud.githubusercontent.com/assets/8545471/4260875/85be5070-3b52-11e4-92d0-bc376ee36215.PNG)

**Comment by tomevoll** [comment]
so both canInsert and isValid must be true for it to accually insert the item, if it is not sided inventory or router is in slot mode, it will get a list of available slots from getSizeInventory().
maybe that is a mistake on my part to not check each side when in sloted mode and expecting isItemValid to return the proper response. 

According to IInventory it should respond with false if anyone try to insert anything non valid in to the slot.

quote from IInventory:
/**
     \* Returns true if automation is allowed to insert the given stack (ignoring stack size) into the given slot.
     */

**Comment by tomevoll** [comment]
i put this in HeatFurnaceInventory.java and that solves the problem
![heatfurnace](https://cloud.githubusercontent.com/assets/8545471/4260942/2ac8e4b0-3b56-11e4-9472-fce277f12304.PNG)

**Comment by tomevoll** [comment]
well that works until i put a heating element in it lol
I'm not sure what you are using that slot for, but if you don't use it at all in heat furnace just always return false on slot 2,

I tried your code above and that crashes to, with a heat element (fork thing for the electric furnace)

**Comment by tomevoll** [comment]
this works, a bit messy, but no transfer can be done if the item is not a instanceof ThermalIsolatorElement
![codefix](https://cloud.githubusercontent.com/assets/8545471/4261033/9a89b85c-3b5a-11e4-903a-211ec887fc0f.PNG)
oh the iso declaration can be removed, i copy pasted part of the code from the processing.

**Comment by tomevoll** [comment]
i  changed my code to check for slots available from all sides when in numbered/sloted mode if the tile is a instance of ISidedInventory, i most likely should have done that to begin with, that should make slot 2 unavalible
