### ISSUE TITLE
Teleporter Bug

### ISSUE THREAD

**Issue by donbubu** [Electrical-Age/ElectricalAge#141]
Hi,
i test it on creative, place a Teleporter and destroy it.. Sometimes i can't place it again on same place, because there transparent block. I cut all transparent blocks down, check it with other blocks that is no one and if i place a transporter again, minecraft crash with this error and the i can never use the place on map again for transporter:

```
java.lang.NullPointerException: Ticking memory connection
    at mods.eln.node.NodeBlock.onBlockPlacedBy(NodeBlock.java:100)
    at mods.eln.node.transparent.TransparentNodeItem.placeBlockAt(TransparentNodeItem.java:80)
    at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:127)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:554)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Dolu1990** [comment]
Hi, thanks for issue, i take a look to :)
