### ISSUE TITLE
Ghost player on the server when disconnect

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#175]
Im found an issue when player use this mod and connect to server with this mod, something build, after disconnect still stay like ghost on the server. Make some debugging and looks like clientside still communicate with server. When connect to another modded or vanilla server, make again ghost player on the connected server. Connection is closed when player shut down Minecraft.

Tested with latest forge server and latest cauldron server too.

**Comment by ghost** [comment]
It is source of problem, why client does not disconnected:

[08:55:04] [Netty Client IO #14/INFO] [STDOUT/]: [mods.eln.misc.Utils:println:81]: Disconnected from server CLIENT
[08:55:04] [Netty Client IO #14/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientDisconnectionFromServerEvent@7181aa11:
java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.GL11.glDeleteLists(GL11.java:714) ~[lwjgl-2.9.1.jar:?]
        at mods.eln.misc.UtilsClient.glDeleteListsAllSafe(UtilsClient.java:616) ~[UtilsClient.class:?]
        at mods.eln.client.ConnectionListener.onDisconnectedFromServerEvent(ConnectionListener.java:41) ~[ConnectionListener.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_169_ConnectionListener_onDisconnectedFromServerEvent_ClientDisconnectionFromServerEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.close(NetworkDispatcher.java:388) [NetworkDispatcher.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeClose(DefaultChannelHandlerContext.java:560) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.close(DefaultChannelHandlerContext.java:545) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeClose(DefaultChannelHandlerContext.java:560) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.access$1200(DefaultChannelHandlerContext.java:28) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext$14.run(DefaultChannelHandlerContext.java:550) [DefaultChannelHandlerContext$14.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]

**Comment by Dolu1990** [comment]
I'm fixing this exeption. coming with next release today.

**Comment by ghost** [comment]
Still not fixed, could you please fix it?

<pre>
diff --git a/src/main/java/mods/eln/misc/UtilsClient.java b/src/main/java/mods/eln/misc/UtilsClient.java
index 6d95843..404a9a5 100644
--- a/src/main/java/mods/eln/misc/UtilsClient.java
+++ b/src/main/java/mods/eln/misc/UtilsClient.java
@@ -612,10 +612,14 @@ public class UtilsClient {
        }
 
        public static void glDeleteListsAllSafe() {
+           try {
                for (Integer id : glListsAllocated) {
                        GL11.glDeleteLists(id, 1);
                }
                glListsAllocated.clear();
+               } catch (Exception e) {
+               //nic
+               }
        }
 
        public static void showItemTooltip(List src,List dst) {
</pre>

This fixed issue for me.

**Comment by Dolu1990** [comment]
Sorry i was sure that i had fix it into r45, but i just see that i have not change any thing to fix it XD

i have take your proposal into ElectricalAge_BETA-1.9_r46.jar that was released some seconde ago.
Thanks for issue
