### ISSUE TITLE
crashes at srart

### ISSUE THREAD

**Issue by shadow5455565** [Electrical-Age/ElectricalAge#178]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/01/15 11.16
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity
    at mods.eln.Eln.registerEnergyConverter(Eln.java:826)
    at mods.eln.Eln.load(Eln.java:640)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: mods.eln.simplenode.energyconverter.EnergyConverterElnToOtherEntity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/power/IPowerEmitter
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.power.IPowerEmitter
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_72, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 238714496 bytes (227 MB) / 535822336 bytes (511 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 38 mods loaded, 38 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1277} [Forge Mod Loader](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1277} [Minecraft Forge](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TooManyItems{1.7.10} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    furnace3d{1.2.0} [Furnace 3D]([1.7.10] 3D Furnace-1.3a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    binocular{1.0} [Binocular](Binocular-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BoomPlus{1.0.0} [BoomPlus](Boom-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.2.6} [BuildCraft](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.2.6} [BC Transport](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.2.6} [BC Silicon](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.2.6} [BC Builders](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.2.6} [BC Energy](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.2.6} [BC Factory](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eureka{2.2} [Eureka](Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bcadditions{2.0-testbuild-1} [Buildcraft Additions](BuildcraftAdditions-1.7.10-2.0-testbuild-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized
    deconstruction{2.2.5} [The Deconstruction Mod](Deconstruction-Table-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Eln{44} [](ElectricalAge_BETA-1.9_r44.jar) Unloaded->Constructed->Pre-initialized->Errored
    IC2{2.2.498-experimental} [IndustrialCraft 2](IndustrialCraft2 [Minecraft 1.7.10][ExMachina].jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{4.0.0} [iChunUtil](Mine Mine No Mi-1.7.10-0.2.3+v3.zip) Unloaded->Constructed->Pre-initialized->Initialized
    wylib{1.0} [WyLib](WyLib 1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mineminenomi{0.2.3} [Mine Mine no Mi](Mine Mine No Mi-1.7.10-0.2.3+v3.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Morph{0.9.0} [Morph](Mine Mine No Mi-1.7.10-0.2.3+v3.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.5.8.59} [ProjectRed](ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    examplemod{1.0} [Example Mod](S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Stefinus Jetpacks{0.6.3} [Stefinus Jetpacks](S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    S3DGM{0.6.3} [Stefinus 3D Gun Mod](S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    punt{1.7.10-10.13.0-14.0} [Punt](Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    whitehall{1.7.10-10.13.0-14.0} [Whitehall](Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    hoy{1.7.10-10.13.0-14.0} [Hoy](Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    smallboats{1.7.10-10.13.0-14.0} [SmallBoats (base)](Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by MyNameIsKodos** [comment]
This is due to ELN using an oudated RF API.

**Comment by madshammy** [comment]
i am guessing this is the same problem.. any thought of when an api update will be coming or what direction you are going.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/11/15 11:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity
    at mods.eln.Eln.registerEnergyConverter(Eln.java:812)
    at mods.eln.Eln.load(Eln.java:628)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: mods.eln.simplenode.energyconverter.EnergyConverterElnToOtherEntity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/power/IPowerEmitter
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.power.IPowerEmitter
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 44 more
Caused by: java.lang.NullPointerException

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 843799000 bytes (804 MB) / 1861746688 bytes (1775 MB) up to 7635730432 bytes (7282 MB)
    JVM Flags: 2 total; -Xmx8192m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 33 mods loaded, 33 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1277} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1277} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997Core{1.0.2.13} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.2.660-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.660-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BetterChests{1.1.1.8} [BetterChests](BetterChests-1.7.10-1.1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    betterstorage{0.11.3.123} [BetterStorage](BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1036-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.3.1} [BuildCraft](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.3.1} [BC Transport](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.3.1} [BC Silicon](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.3.1} [BC Builders](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.3.1} [BC Energy](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.3.1} [BC Factory](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.3.4.2} [Carpenter's Blocks](Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.1.320} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{2.2.1} [Chisel](Chisel 2-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChiselFacades{1.7.10-2.7-cricket} [Chisel Facades](ChiselFacades-1.7.10-2.7-cricket.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Eln{41} [Electrical Age](ElectricalAge_BETA-1.9_r41.jar) Unloaded->Constructed->Pre-initialized->Errored
    McMultipart{1.1.1.320} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.1.320} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle Environment: Environment healthy.

**Comment by MyNameIsKodos** [comment]
Judging by his MCF profile, I'm not sure how long it will be...

ElectricalAge
Registered Member
Member for 7 months and 2 days 
Last active Sat, Dec, 20 2014 14:32:25

**Comment by Dolu1990** [comment]
i fix that now, releasing it today

**Comment by madshammy** [comment]
looks like your r45 works wonderful thx man great mod keep up the great work.

**Comment by shadow5455565** [comment]
WorKs forse me, too

**Comment by MyNameIsKodos** [comment]
Thanks for updating, Dolu =)

Regarding your server error, did you make sure to change the value in eula.txt to true?  A -lot- of people forget to do that, myself included.
