### ISSUE TITLE
Missing Texture Error (java.io.FileNotFoundException)

### ISSUE THREAD

**Issue by XxCoolGamesxX** [Electrical-Age/ElectricalAge#197]
Hey,
Not use the Optifine and not use a Resource Pack. Only of Minecraft
Use: ELECTRICALAGE_BETA-1.9_R46.
Forge: 10.13.2.1291

Here error:

```
[17:42:56] [Client thread/ERROR]: Using missing texture, unable to load eln:textures/blocks/removedfrommodcopperthermalcable.png
java.io.FileNotFoundException: eln:textures/blocks/removedfrommodcopperthermalcable.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
    at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

```
[17:42:58] [Client thread/ERROR]: Using missing texture, unable to load eln:textures/blocks/800vdefenceturret.png
java.io.FileNotFoundException: eln:textures/blocks/800vdefenceturret.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
    at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

```
[20:27:43] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_840_OreEln.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_840_OreEln.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
    at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
    at com.mumfrey.liteloader.client.GameEngineClient.refreshResources(GameEngineClient.java:62) [GameEngineClient.class:1.7.10_04]
    at com.mumfrey.liteloader.client.ClientEvents.onStartupComplete(ClientEvents.java:236) [ClientEvents.class:1.7.10_04]
    at com.mumfrey.liteloader.client.CallbackProxyClient.onStartupComplete(CallbackProxyClient.java:48) [CallbackProxyClient.class:1.7.10_04]
    at com.mumfrey.liteloader.core.event.EventProxy.$event00000(EventProxy.java:211) [EventProxy.class:1.7.10_04]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:573) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]   
```

**Comment by DrummingFish** [comment]
Have you tried removing your shaders mod?

**Comment by DrummingFish** [comment]
And possibly Liteloader.

**Comment by XxCoolGamesxX** [comment]
Look in the Mod folder (assets\eln\textures\blocks) the removedfrommodcopperthermalcable.png and 800vdefenceturret.png not on it.

The minecraft:textures/blocks/MISSING_ICON_BLOCK_840_OreEln.png:
It removing the shaders mod and Liteloader but the error show up.

**Comment by cm0x4D** [comment]
] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: The following texture errors were found.
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN minecraft
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:   domain minecraft is missing 1 texture
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     domain minecraft has 1 location:
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:       unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain minecraft are:
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/MISSING_ICON_BLOCK_169_OreEln.png
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain minecraft
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN eln
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:   domain eln is missing 2 textures
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     domain eln has 1 location:
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:       mod Eln resources at /Users/clm/Library/Application Support/minecraft/mods/ElectricalAge_BETA-1.9_r51.jar
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain eln are:
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/800vdefenceturret.png
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/removedfrommodcopperthermalcable.png
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain eln
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[20:00:51] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
