### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#208]
When I try to Play minecraft it doesn't start.I see this text in my launcher:

[18:22:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:22:31] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:22:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[18:22:31] [main/INFO] [FML]: Forge Mod Loader version 7.2.211.1121 for Minecraft 1.7.2 loading
[18:22:31] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[18:22:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:22:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[18:22:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:22:31] [main/ERROR] [LaunchWrapper]: Unable to launch
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_25]
    at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
what does this mean? I'm using ElectricalAge_BETA-1.5_r10.(because I wanted to see the differents between older and newer Versions ^^^)

**Comment by bloxgate** [comment]
Java 8 update 25 is not compatible with that minecraft forge version. Either install the legacy mod fixer if you can find a copy or update to a version of forge supporting java versions greater than 8u11.

**Comment by yannic312** [comment]
ok thanks :)
