### ISSUE TITLE
NPE @ energyconverter in 1.9-r46

### ISSUE THREAD

**Issue by PhoenixtheII** [Electrical-Age/ElectricalAge#229]
java.lang.NullPointerException
    at mods.eln.simplenode.energyconverter.EnergyConverterElnToOtherEntity.getSourceTier(EnergyConverterElnToOtherEntity.java:120) ~[EnergyConverterElnToOtherEntity.class:?]
    at ic2.core.energy.Grid.prepareCalculation(Grid.java:278) ~[Grid.class:?]
    at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:403) ~[EnergyNetLocal.class:?]
    at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:69) ~[EnergyNetGlobal.class:?]
    at ic2.core.TickHandler.onWorldTick(TickHandler.java:79) ~[TickHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_24_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by PhoenixtheII** [comment]
INDUSTRIALCRAFT-2-2.2.720-EXPERIMENTAL.jar, for IC2 version :)

**Comment by PhoenixtheII** [comment]
Apparently, nobody will fix, closing
