### ISSUE TITLE
CRASH: Recipe Tab (Advanced Chip Recipe)

### ISSUE THREAD

**Issue by BroBeans** [Electrical-Age/ElectricalAge#23]
You know, how when you press "X" it opens a tab where you can find all the recipes for things. Well i went to the "Transportation Machine" Recipe > "Advanced Chip" > CRASH

Crash Report:

--- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/29/14 10:58 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at mods.eln.misc.Utils.getItemStackGrid(Utils.java:1418)
    at mods.eln.wiki.ItemDefault.func_73866_w_(ItemDefault.java:109)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:732)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:398)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:334)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2480)
    at mods.eln.misc.Utils.clientOpenGui(Utils.java:1241)
    at mods.eln.wiki.GuiItemStack.imouseClicked(GuiItemStack.java:121)
    at mods.eln.wiki.GuiVerticalExtender.imouseClicked(GuiVerticalExtender.java:165)
    at mods.eln.gui.GuiHelper.mouseClicked(GuiHelper.java:198)
    at mods.eln.gui.GuiScreenEln.func_73864_a(GuiScreenEln.java:59)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1566)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at mods.eln.misc.Utils.getItemStackGrid(Utils.java:1418)
    at mods.eln.wiki.ItemDefault.func_73866_w_(ItemDefault.java:109)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:732)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:398)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:334)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2480)
    at mods.eln.misc.Utils.clientOpenGui(Utils.java:1241)
    at mods.eln.wiki.GuiItemStack.imouseClicked(GuiItemStack.java:121)
    at mods.eln.wiki.GuiVerticalExtender.imouseClicked(GuiVerticalExtender.java:165)
    at mods.eln.gui.GuiHelper.mouseClicked(GuiHelper.java:198)
    at mods.eln.gui.GuiScreenEln.func_73864_a(GuiScreenEln.java:59)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)

-- Affected screen --
Details:
    Screen name: mods.eln.wiki.ItemDefault

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['TheClassyMonster'/123, l='MpServer', x=1178.30, y=5.62, z=-31.89]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1163,4,-42), Chunk: (at 11,0,6 in 72,-3; contains blocks 1152,0,-48 to 1167,255,-33), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
    Level time: 402964 game time, 40926 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 62 total; [EntityClientPlayerMP['TheClassyMonster'/123, l='MpServer', x=1178.30, y=5.62, z=-31.89], EntityChicken['Chicken'/23, l='MpServer', x=1118.53, y=4.00, z=-106.47], EntitySkeleton['Skeleton'/25, l='MpServer', x=1105.94, y=4.00, z=12.47], EntitySkeleton['Skeleton'/24, l='MpServer', x=1109.00, y=4.00, z=-89.50], EntitySkeleton['Skeleton'/26, l='MpServer', x=1115.34, y=4.00, z=-2.16], EntitySkeleton['Skeleton'/29, l='MpServer', x=1123.44, y=4.00, z=-60.91], EntityZombie['Zombie'/28, l='MpServer', x=1134.50, y=4.00, z=-87.50], EntityChicken['Chicken'/31, l='MpServer', x=1121.63, y=4.00, z=-43.56], EntityCreeper['Creeper'/30, l='MpServer', x=1127.50, y=4.00, z=-53.50], EntityCreeper['Creeper'/34, l='MpServer', x=1121.50, y=4.00, z=16.50], EntitySkeleton['Skeleton'/35, l='MpServer', x=1126.91, y=4.00, z=22.34], EntityChicken['Chicken'/32, l='MpServer', x=1123.66, y=4.00, z=-29.41], EntitySkeleton['Skeleton'/33, l='MpServer', x=1123.88, y=4.00, z=-31.47], EntityCow['Cow'/38, l='MpServer', x=1134.78, y=4.00, z=-96.78], EntitySkeleton['Skeleton'/39, l='MpServer', x=1134.78, y=4.00, z=-74.69], EntitySkeleton['Skeleton'/36, l='MpServer', x=1126.25, y=4.00, z=39.22], EntityCow['Cow'/42, l='MpServer', x=1153.97, y=4.00, z=-100.97], EntityChicken['Chicken'/43, l='MpServer', x=1161.47, y=4.00, z=-88.47], EntitySpider['Spider'/40, l='MpServer', x=1148.16, y=4.00, z=-18.53], EntityChicken['Chicken'/46, l='MpServer', x=1153.53, y=4.00, z=-27.78], EntityChicken['Chicken'/47, l='MpServer', x=1155.91, y=4.00, z=-30.41], EntityEnderman['Enderman'/44, l='MpServer', x=1153.59, y=4.00, z=-58.00], EntityChicken['Chicken'/45, l='MpServer', x=1152.78, y=4.00, z=-27.78], EntityItem['item.tile.torch'/51, l='MpServer', x=1159.41, y=4.13, z=-26.13], EntityChicken['Chicken'/50, l='MpServer', x=1155.47, y=4.00, z=-31.22], EntityChicken['Chicken'/49, l='MpServer', x=1152.78, y=4.00, z=-31.22], EntityChicken['Chicken'/48, l='MpServer', x=1154.47, y=4.00, z=-27.78], EntitySkeleton['Skeleton'/54, l='MpServer', x=1166.78, y=4.00, z=-5.66], EntityChicken['Chicken'/53, l='MpServer', x=1155.41, y=4.00, z=-30.56], EntityChicken['Chicken'/52, l='MpServer', x=1156.72, y=4.00, z=-31.47], EntitySkeleton['Skeleton'/59, l='MpServer', x=1172.09, y=4.00, z=-87.09], EntitySkeleton['Skeleton'/58, l='MpServer', x=1180.72, y=4.00, z=-100.75], EntityCreeper['Creeper'/57, l='MpServer', x=1183.03, y=4.00, z=-105.34], EntitySpider['Spider'/56, l='MpServer', x=1169.75, y=4.00, z=-111.56], EntitySpider['Spider'/63, l='MpServer', x=1175.34, y=4.00, z=-93.78], EntityCreeper['Creeper'/62, l='MpServer', x=1173.78, y=4.00, z=-89.13], EntityCreeper['Creeper'/61, l='MpServer', x=1175.47, y=4.00, z=-95.31], EntitySpider['Spider'/60, l='MpServer', x=1171.03, y=4.00, z=-88.38], EntitySkeleton['Skeleton'/68, l='MpServer', x=1181.44, y=4.00, z=2.09], EntityCreeper['Creeper'/69, l='MpServer', x=1173.50, y=4.00, z=-7.50], EntitySpider['Spider'/64, l='MpServer', x=1174.50, y=4.00, z=-100.53], EntitySpider['Spider'/65, l='MpServer', x=1171.97, y=4.00, z=-64.22], EntitySpider['Spider'/67, l='MpServer', x=1170.98, y=4.00, z=-29.75], EntitySkeleton['Skeleton'/76, l='MpServer', x=1202.72, y=4.00, z=-59.88], EntityZombie['Zombie'/77, l='MpServer', x=1211.25, y=4.00, z=-29.13], EntityHorse['Horse'/78, l='MpServer', x=1206.00, y=4.00, z=15.09], EntityCreeper['Creeper'/72, l='MpServer', x=1184.97, y=4.00, z=-103.75], EntityZombie['Zombie'/73, l='MpServer', x=1199.28, y=4.00, z=-66.09], EntitySkeleton['Skeleton'/74, l='MpServer', x=1193.09, y=4.00, z=-12.34], EntitySpider['Spider'/75, l='MpServer', x=1193.00, y=4.00, z=-6.06], EntityCreeper['Creeper'/85, l='MpServer', x=1225.88, y=4.00, z=-79.25], EntityCreeper['Creeper'/84, l='MpServer', x=1230.72, y=4.00, z=-73.13], EntityChicken['Chicken'/87, l='MpServer', x=1223.53, y=4.00, z=-17.53], EntitySpider['Spider'/86, l='MpServer', x=1230.09, y=4.00, z=-76.34], EntitySpider['Spider'/81, l='MpServer', x=1227.84, y=4.00, z=-89.44], EntityZombie['Zombie'/83, l='MpServer', x=1222.50, y=4.00, z=-73.50], EntitySkeleton['Skeleton'/82, l='MpServer', x=1229.50, y=4.00, z=-68.50], EntitySpider['Spider'/93, l='MpServer', x=1251.50, y=4.00, z=-83.50], EntityZombie['Zombie'/92, l='MpServer', x=1257.50, y=4.00, z=-93.50], EntityCreeper['Creeper'/95, l='MpServer', x=1249.56, y=4.00, z=-78.97], EntityHorse['Horse'/88, l='MpServer', x=1221.63, y=4.00, z=-30.03], EntityZombie['Zombie'/96, l='MpServer', x=1251.50, y=4.00, z=39.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_07, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 260760008 bytes (248 MB) / 544014336 bytes (518 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 19636 (1099616 bytes; 1 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Eln{BETA-1.1.2} [Electrical Age](ElectricalAge_BETA_1.1.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.965
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 885 (49560 bytes; 0 MB) allocated, 12 (672 bytes; 0 MB) used

**Comment by Dolu1990** [comment]
i explore that this night ^^ Thanks for report
