### ISSUE TITLE
NPE while .getCurrentLanguage

### ISSUE THREAD

**Issue by Levvy055** [Electrical-Age/ElectricalAge#262]
When I run project from Eclipse I get:
NullPointerException
    at cpw.mods.fml.client.FMLClientHandler.getCurrentLanguage(FMLClientHandler.java:622) ~[forgeSrc-1.7.10-10.13.4.1481-1.7.10.jar:?]
    at cpw.mods.fml.common.FMLCommonHandler.getCurrentLanguage(FMLCommonHandler.java:521) ~[forgeSrc-1.7.10-10.13.4.1481-1.7.10.jar:?]
    at cpw.mods.fml.common.registry.LanguageRegistry.getStringLocalization(LanguageRegistry.java:63) ~[forgeSrc-1.7.10-10.13.4.1481-1.7.10.jar:?]
    at mods.eln.misc.I18N.getString(I18N.java:17) ~[bin/:?]
Full log: http://pastebin.com/F44Diz96

Looks like LanguageRegistry is trying to gget something to early. And I am also interested if this I18N is needed there.
When updated forge got the same exception.

**Comment by cm0x4D** [comment]
Has been fixed afaik.
