### ISSUE TITLE
Client got kicked with "internal server error" message when breaking a block underneath a cable on a server

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#34]
I've turned off debug message but there are still stuff shown when placing cables like:

2014-05-18 00:15:40 [INFO] createSubBlock 2048 ZN
2014-05-18 00:15:41 [INFO] Node::constructor( meta = 2048)
2014-05-18 00:15:41 [INFO] Node destroy error already destroy
2014-05-18 00:15:41 [INFO] createSubBlock 2048 XN
2014-05-18 00:15:42 [INFO] createSubBlock 2048 YN
2014-05-18 00:15:43 [INFO] Node::constructor( meta = 2048)
2014-05-18 00:15:43 [INFO] Node destroy error already destroy
2014-05-18 00:15:43 [INFO] createSubBlock 2048 XN
2014-05-18 00:15:44 [INFO] createSubBlock 2048 ZN
2014-05-18 00:15:46 [INFO] Node::constructor( meta = 2048)
2014-05-18 00:15:46 [INFO] Node destroy error already destroy
2014-05-18 00:15:46 [INFO] createSubBlock 2048 YN
2014-05-18 00:15:49 [INFO] deleteSubBlock  XN

In the server console the following message is shown when player got kicked, when I re-logon the cable over the broken block is not removed correctly.
this does not happen on ssp

2014-05-18 00:15:49 [WARNING] Failed to handle packet for wormzjl/127.0.0.1: net.minecraft.util.ReportedException: Exception while updating neighbours
net.minecraft.util.ReportedException: Exception while updating neighbours
    at net.minecraft.world.World.func_72821_m(World.java:1219)
    at net.minecraft.world.World.func_72898_h(World.java:1127)
    at net.minecraft.world.World.func_72851_f(World.java:1081)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:908)
    at net.minecraft.world.World.func_72832_d(World.java:886)
    at net.minecraft.world.World.func_94571_i(World.java:1028)
    at net.minecraft.block.Block.removeBlockByPlayer(Block.java:1711)
    at net.minecraft.item.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:346)
    at net.minecraft.item.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:387)
    at net.minecraft.item.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:200)
    at net.minecraft.network.NetServerHandler.func_72510_a(NetServerHandler.java:771)
    at net.minecraft.network.packet.Packet14BlockDig.func_73279_a(Packet14BlockDig.java:67)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at mods.eln.misc.Utils.isCreative(Utils.java:912)
    at mods.eln.misc.Utils.mustDropItem(Utils.java:924)
    at mods.eln.node.SixNodeElement.destroy(SixNodeElement.java:199)
    at mods.eln.node.SixNode.deleteSubBlock(SixNode.java:172)
    at mods.eln.node.SixNodeBlock.func_71863_a(SixNodeBlock.java:228)
    at net.minecraft.world.World.func_72821_m(World.java:1200)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more

**Comment by Dolu1990** [comment]
Cool, isssue ^^
Thanks for report, i explore that now

**Comment by Dolu1990** [comment]
Some debug message remain when debug is off, it's juste because there are many place where i must change that, and i have miss them. (in progress)

**Comment by Dolu1990** [comment]
New release ElectricalAge_BETA_1.2.0a fix server crash
Thanks for report, 
Bug was because when you run the server, some code is removed by minecraft (client/server side)
We have made a lot of play with SSP that open his world to lan, but not with dedicated server. 
If you have other issue, to wait that is fixed, you can try run your world in SSP with map open to lan.

**Comment by Dolu1990** [comment]
new release  ElectricalAge_BETA_1.2.0b fix all
and now, all debug message (with any exeption) get the debug feild of .config file
