### ISSUE TITLE
Crash with certain items on in-game wiki

### ISSUE THREAD

**Issue by bloxgate** [Electrical-Age/ElectricalAge#342]
Clicking on an item with a large number of recipes (such as redstone) can cause the game to crash with the following error:

``` java
java.lang.IllegalStateException: Already tesselating!

    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
    at net.minecraft.client.gui.Gui.func_73729_b(SourceFile:106)
    at net.minecraft.client.gui.GuiButton.func_146112_a(GuiButton.java:75)
    at mods.eln.gui.GuiButtonEln.idraw(GuiButtonEln.java:32)
    at mods.eln.gui.GuiHelper.draw(GuiHelper.java:135)
    at mods.eln.gui.GuiScreenEln.func_73863_a(GuiScreenEln.java:69)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by cm0x4D** [comment]
I can not reproduce the bug with actual dev version, which version of the mod had this behavior?

**Comment by bloxgate** [comment]
Last time I had the issue was in r50
