### ISSUE TITLE
Possible infinite loop on mods.eln.misc.Utils.traceRay

### ISSUE THREAD

**Issue by Polyana-Fontes** [Electrical-Age/ElectricalAge#344]
My server was running fine when suddenly it stopped and all players connection were lost, than the server just stopped there for minutes.

After I restarted, it stopped right after the startup process, I left it running for few minutes but nothing changed, so probably an infinite loop were happening on the server thread.

Then I sent a QUIT signal to the java process (kill -3 PID) to display a thread dump and this is what was hanging the Server thread:

```
"Server thread" #20 prio=5 os_prio=0 tid=0x00007f8298ec3000 nid=0x29b7 runnable [0x00007f827ca49000]
   java.lang.Thread.State: RUNNABLE
        at mods.eln.misc.Utils.traceRay(Utils.java:922)
        at mods.eln.sixnode.electricalentitysensor.ElectricalEntitySensorSlowProcess.process(ElectricalEntitySensorSlowProcess.java:75)
        at mods.eln.sim.Simulator.tick(Simulator.java:427)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_Simulator_tick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Polyana-Fontes** [comment]
The problem is happening at this line:
https://github.com/Dolu1990/ElectricalAge/blob/BETA-1.10/src/main/java/mods/eln/misc/Utils.java#L922

**Comment by Dolu1990** [comment]
It's completly true.
Thanks for this spot :)

**Comment by Safranil** [comment]
Hello,
I discovered this problem on my server after placing some blocks (daylight sensor, solar panels) and my server is now frozen :disappointed_relieved:.

Can you make a release with this correction ?
