### ISSUE TITLE
A couple of Errors and Console spam that fills log file up fast while running with mod.

### ISSUE THREAD

**Issue by crunkazcanbe** [Electrical-Age/ElectricalAge#35]
2014-05-18 16:49:27 [INFO] [STDOUT] Loading World: local/New World
2014-05-18 16:49:27 [INFO] [STDERR] java.lang.NoSuchFieldException: persistenceRequired
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.Class.getDeclaredField(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at mods.eln.entity.ReplicatorEntity.<init>(ReplicatorEntity.java:52)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Constructor.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.loadSpawners(ItemMobSpawner.java:132)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.<init>(ItemMobSpawner.java:37)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo$5.run(ItemInfo.java:273)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.core.featurehack.GameDataManipulator.createHiddenItem(GameDataManipulator.java:15)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo.addMobSpawnerItem(ItemInfo.java:267)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo.load(ItemInfo.java:104)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:293)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:237)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:127)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEICPH.handlePacket(NEICPH.java:29)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.lib.packet.PacketCustom$ClientPacketHandler.handle(PacketCustom.java:166)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.lib.packet.PacketCustom$CustomPacketHandler.onPacketData(PacketCustom.java:136)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1967)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.main.Main.main(SourceFile:101)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.EntryPoint.listen(EntryPoint.java:165)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.EntryPoint.main(EntryPoint.java:54)
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4375157269042467 Derivate : 0.0065643073515113184 EPmax : 11.500125815233973
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4375157269042467 Derivate : 0.04365349288629583 EPmax : 11.500125815233973
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4375157269042467 Derivate : -0.07113790476972315 EPmax : 11.500125815233973
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.3368896260209493 Derivate : -0.10305840046774967 EPmax : 10.695117008167594
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4483450909155011 Derivate : -0.07663221988999455 EPmax : 11.586760727324009
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4483450909155011 Derivate : 0.002809014828990569 EPmax : 11.586760727324009
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.4483450909155011 Derivate : -0.0011432915734375035 EPmax : 11.586760727324009
2014-05-18 16:49:28 [INFO] [STDOUT] Wind : 1.346960934551416 Derivate : -0.02220709310366291 EPmax : 10.775687476411328
2014-05-18 16:49:29 [INFO] [STDOUT] Wind : 1.4517148139028109 Derivate : 0.045447442000526396 EPmax : 11.613718511222487
2014-05-18 16:49:29 [INFO] [STDOUT] Wind : 1.4517148139028109 Derivate : 0.09353316319879106 EPmax : 11.613718511222487
2014-05-18 16:49:29 [INFO] [STDOUT] Wind : 1.4517148139028109 Derivate : 0.05444353870187056 EPmax : 11.613718511222487
2014-05-18 16:49:29 [INFO] [STDOUT] Wind : 1.350094776929614 Derivate : 0.06663362393342961 EPmax : 10.800758215436913
2014-05-18 16:49:29 [INFO] [Minecraft-Server] Saving and pausing game...
2014-05-18 16:49:29 [INFO] [Minecraft-Server] Saving chunks for level 'New World'/Overworld
2014-05-18 16:49:29 [INFO] [STDOUT] ZP
2014-05-18 16:49:29 [INFO] [STDOUT] ZP
2014-05-18 16:49:29 [INFO] [STDOUT] ZP
2014-05-18 16:49:29 [INFO] [STDOUT] ZP
2014-05-18 16:49:29 [INFO] [Minecraft-Server] Saving chunks for level 'New World'/Nether
2014-05-18 16:49:29 [INFO] [Minecraft-Server] Saving chunks for level 'New World'/The End
2014-05-18 16:49:48 [INFO] [STDOUT] Wind : 1.4569439279632848 Derivate : -0.04312482286649325 EPmax : 11.655551423706278
2014-05-18 16:49:48 [INFO] [STDOUT] Wind : 1.4569439279632848 Derivate : 0.15092414794449932 EPmax : 11.655551423706278
2014-05-18 16:49:48 [INFO] [STDOUT] Wind : 1.4569439279632848 Derivate : 0.020904739056105497 EPmax : 11.655551423706278
2014-05-18 16:49:48 [INFO] [STDOUT] Wind : 1.3549578530058548 Derivate : -0.02445674501274707 EPmax : 10.839662824046838
2014-05-18 16:49:49 [INFO] [STDOUT] Inserted super call into axm.c
2014-05-18 16:49:49 [INFO] [STDERR] java.lang.NoSuchFieldException: persistenceRequired
2014-05-18 16:49:49 [INFO] [STDERR] at java.lang.Class.getDeclaredField(Unknown Source)
2014-05-18 16:49:49 [INFO] [STDERR] at mods.eln.entity.ReplicatorEntity.<init>(ReplicatorEntity.java:52)
2014-05-18 16:49:49 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-05-18 16:49:49 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:49 [INFO] [STDERR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:49 [INFO] [STDERR] at java.lang.reflect.Constructor.newInstance(Unknown Source)
2014-05-18 16:49:49 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.getEntity(ItemMobSpawner.java:99)
2014-05-18 16:49:49 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.func_77624_a(ItemMobSpawner.java:82)
2014-05-18 16:49:49 [INFO] [STDERR] at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:663)
2014-05-18 16:49:49 [INFO] [STDERR] at codechicken.nei.forge.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:154)
2014-05-18 16:49:49 [INFO] [STDERR] at codechicken.nei.forge.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:200)
2014-05-18 16:49:49 [INFO] [STDERR] at codechicken.nei.ItemList$ThreadLoadItems.run(ItemList.java:367)
2014-05-18 16:49:49 [INFO] [STDOUT] Wind : 1.4594331881580405 Derivate : -0.019800267569855676 EPmax : 11.675465505264324
2014-05-18 16:49:49 [INFO] [STDOUT] Wind : 1.4594331881580405 Derivate : 0.13203500940764895 EPmax : 11.675465505264324
2014-05-18 16:49:49 [INFO] [STDOUT] Wind : 1.4594331881580405 Derivate : 0.022410891701910688 EPmax : 11.675465505264324
2014-05-18 16:49:49 [INFO] [STDOUT] Wind : 1.3572728649869776 Derivate : -0.024461949701085627 EPmax : 10.858182919895821
2014-05-18 16:49:50 [INFO] [STDOUT] Wind : 1.4572613694546743 Derivate : -0.01697308074591801 EPmax : 11.658090955637395
2014-05-18 16:49:50 [INFO] [STDOUT] Wind : 1.4572613694546743 Derivate : 0.09574214726127296 EPmax : 11.658090955637395
2014-05-18 16:49:50 [INFO] [STDOUT] Wind : 1.4572613694546743 Derivate : -0.026587319048797933 EPmax : 11.658090955637395
2014-05-18 16:49:50 [INFO] [STDOUT] Wind : 1.355253073592847 Derivate : 0.06414874251322242 EPmax : 10.842024588742776
2014-05-18 16:49:51 [INFO] [STDOUT] Wind : 1.4541579022008855 Derivate : 0.06254546664522864 EPmax : 11.633263217607084
2014-05-18 16:49:51 [INFO] [STDOUT] Wind : 1.4541579022008855 Derivate : -0.01498476089529406 EPmax : 11.633263217607084
2014-05-18 16:49:51 [INFO] [STDOUT] Wind : 1.4541579022008855 Derivate : -0.037063716173771646 EPmax : 11.633263217607084
2014-05-18 16:49:51 [INFO] [STDOUT] Wind : 1.3523668490468235 Derivate : -0.00953276826925701 EPmax : 10.818934792374588
2014-05-18 16:49:52 [INFO] [STDOUT] Wind : 1.4443662392583447 Derivate : -0.035660672372949544 EPmax : 11.554929914066758
2014-05-18 16:49:52 [INFO] [STDOUT] Wind : 1.4443662392583447 Derivate : -0.09872330139480473 EPmax : 11.554929914066758
2014-05-18 16:49:52 [INFO] [STDOUT] Wind : 1.4443662392583447 Derivate : -0.09684243454211033 EPmax : 11.554929914066758
2014-05-18 16:49:52 [INFO] [STDOUT] Wind : 1.3432606025102605 Derivate : 0.08187805846917658 EPmax : 10.746084820082084
2014-05-18 16:49:53 [INFO] [STDOUT] EnvironementWindFactor : 1.0
2014-05-18 16:49:53 [INFO] [STDOUT] Wind : 1.4332774091791638 Derivate : 0.05228732742943269 EPmax : 11.46621927343331
2014-05-18 16:49:53 [INFO] [STDOUT] Wind : 1.4332774091791638 Derivate : -0.03558187817870761 EPmax : 11.46621927343331
2014-05-18 16:49:53 [INFO] [STDOUT] Wind : 1.4332774091791638 Derivate : 0.017087737457823368 EPmax : 11.46621927343331
2014-05-18 16:49:53 [INFO] [STDOUT] Wind : 1.3329479905366222 Derivate : 0.09867621411321188 EPmax : 10.663583924292977
2014-05-18 16:49:54 [INFO] [STDOUT] Wind : 1.4170138500092337 Derivate : 0.05215358751165123 EPmax : 11.33611080007387
2014-05-18 16:49:54 [INFO] [STDOUT] Wind : 1.4170138500092337 Derivate : -0.10143636944709994 EPmax : 11.33611080007387
2014-05-18 16:49:54 [INFO] [STDOUT] Wind : 1.4170138500092337 Derivate : -0.0735385746872206 EPmax : 11.33611080007387
2014-05-18 16:49:54 [INFO] [STDOUT] Wind : 1.3178228805085872 Derivate : 0.12146063066814193 EPmax : 10.542583044068698
2014-05-18 16:49:55 [INFO] [STDOUT] EnvironementWindFactor : 1.0
2014-05-18 16:49:55 [INFO] [STDOUT] EnvironementWindFactor : 1.0
2014-05-18 16:49:55 [INFO] [STDOUT] Wind : 1.3905745452197298 Derivate : -0.04123224456312414 EPmax : 11.124596361757838
2014-05-18 16:49:55 [INFO] [STDOUT] Wind : 1.3905745452197298 Derivate : -0.0732549460217385 EPmax : 11.124596361757838
2014-05-18 16:49:55 [INFO] [STDOUT] Wind : 1.3905745452197298 Derivate : -0.04506730869789662 EPmax : 11.124596361757838
2014-05-18 16:49:55 [INFO] [STDOUT] Wind : 1.2932343270543487 Derivate : 0.06337268610835686 EPmax : 10.34587461643479
2014-05-18 16:49:56 [INFO] [STDOUT] EnvironementWindFactor : 0.9299999999999999
2014-05-18 16:49:56 [INFO] [STDOUT] Wind : 1.3474499947911909 Derivate : 0.06052021647321287 EPmax : 10.779599958329527
2014-05-18 16:49:56 [INFO] [STDOUT] Wind : 1.3474499947911909 Derivate : 0.042429910929089105 EPmax : 10.779599958329527
2014-05-18 16:49:56 [INFO] [STDOUT] Wind : 1.3474499947911909 Derivate : -0.12903304667825644 EPmax : 10.779599958329527
2014-05-18 16:49:56 [INFO] [STDOUT] Wind : 1.2531284951558075 Derivate : 0.0239664498722108 EPmax : 10.02502796124646
2014-05-18 16:49:57 [INFO] [STDOUT] Wind : 1.2981586792676938 Derivate : -0.04575974799593012 EPmax : 10.38526943414155
2014-05-18 16:49:57 [INFO] [STDOUT] Wind : 1.2981586792676938 Derivate : -0.01696002449468459 EPmax : 10.38526943414155
2014-05-18 16:49:57 [INFO] [STDOUT] Wind : 1.2981586792676938 Derivate : -0.06713837069723913 EPmax : 10.38526943414155
2014-05-18 16:49:57 [INFO] [STDOUT] Wind : 1.207287571718955 Derivate : 0.11607712053200749 EPmax : 9.65830057375164
2014-05-18 16:49:58 [INFO] [STDOUT] Wind : 1.2438497691077952 Derivate : -0.12081601034659274 EPmax : 9.950798152862362
2014-05-18 16:49:58 [INFO] [STDOUT] Wind : 1.2438497691077952 Derivate : 0.06967787111487146 EPmax : 9.950798152862362
2014-05-18 16:49:58 [INFO] [STDOUT] Wind : 1.2438497691077952 Derivate : -0.0519860675115693 EPmax : 9.950798152862362
2014-05-18 16:49:58 [INFO] [STDOUT] Wind : 1.1567802852702496 Derivate : -0.0038014121040689935 EPmax : 9.254242282161997
2014-05-18 16:49:59 [INFO] [STDOUT] Wind : 1.1945778620325296 Derivate : -0.010738173028773085 EPmax : 9.556622896260237
2014-05-18 16:49:59 [INFO] [STDOUT] Wind : 1.1945778620325296 Derivate : 0.01224872843188695 EPmax : 9.556622896260237
2014-05-18 16:49:59 [INFO] [STDOUT] Wind : 1.1945778620325296 Derivate : -0.06865054287221478 EPmax : 9.556622896260237
2014-05-18 16:49:59 [INFO] [STDOUT] Wind : 1.1109574116902525 Derivate : -0.08993046648071913 EPmax : 8.88765929352202
2014-05-18 16:50:00 [INFO] [STDOUT] Wind : 1.1434459700683661 Derivate : 0.05534820872956977 EPmax : 9.147567760546929
2014-05-18 16:50:00 [INFO] [STDOUT] Wind : 1.1434459700683661 Derivate : -0.08445834093457032 EPmax : 9.147567760546929
2014-05-18 16:50:00 [INFO] [STDOUT] Wind : 1.1434459700683661 Derivate : -0.10342857571132345 EPmax : 9.147567760546929
2014-05-18 16:50:00 [INFO] [STDOUT] Wind : 1.0634047521635803 Derivate : 0.016249955705884805 EPmax : 8.507238017308643
2014-05-18 16:50:01 [INFO] [STDOUT] EnvironementWindFactor : 1.0

**Comment by crunkazcanbe** [comment]
This is the error i get every time i log into my world . And from what i can tell is the mod is stuck in debug mode even though in the config it is false because it is showing everything i do in the console i watch it while playing.

2014-05-18 16:49:27 [INFO] [STDERR] java.lang.NoSuchFieldException: persistenceRequired
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.Class.getDeclaredField(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at mods.eln.entity.ReplicatorEntity.<init>(ReplicatorEntity.java:52)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Constructor.newInstance(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.loadSpawners(ItemMobSpawner.java:132)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.ItemMobSpawner.<init>(ItemMobSpawner.java:37)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo$5.run(ItemInfo.java:273)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.core.featurehack.GameDataManipulator.createHiddenItem(GameDataManipulator.java:15)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo.addMobSpawnerItem(ItemInfo.java:267)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.api.ItemInfo.load(ItemInfo.java:104)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:293)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:237)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:127)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.nei.NEICPH.handlePacket(NEICPH.java:29)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.lib.packet.PacketCustom$ClientPacketHandler.handle(PacketCustom.java:166)
2014-05-18 16:49:27 [INFO] [STDERR] at codechicken.lib.packet.PacketCustom$CustomPacketHandler.onPacketData(PacketCustom.java:136)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-05-18 16:49:27 [INFO] [STDERR] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1967)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.client.main.Main.main(SourceFile:101)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-05-18 16:49:27 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.EntryPoint.listen(EntryPoint.java:165)
2014-05-18 16:49:27 [INFO] [STDERR] at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by Dolu1990** [comment]
Hi, i explore that now, That happend in SSP ?
Thanks for issue.

**Comment by Dolu1990** [comment]
for debug spam, it's in pipe to remove some log

**Comment by Dolu1990** [comment]
For you issue, that seem to be the interaction between NEI and electrical age, it is possible ? do you have the same issue if you don't use others mod ?
It's very strang. in any case it's nothing critical for you map, nothing that can break you map.

**Comment by Dolu1990** [comment]
Huuuu, now i can reproduct issue, i investigate !

**Comment by Dolu1990** [comment]
Oky now all is fixed. New release ElectricalAge_BETA_1.2.0b : D
Fix java error 
remove all debug console print when debug mode is desable

Thanks again for issue : D

**Comment by crunkazcanbe** [comment]
Glad I could help I love the mod and find it to be my fav mod out of 500+ mods I have tried its the most realistic this and applied energestics is my fav mod I have tried and use ic2 , buildcraft, thermal expansion, and quit a few ue mods resonant induction and mekanism are in my private mod pack. I have a city like new York city I have been working on for almost 2 years now along with a mod pack I made with 198 mods in it and this is by far the best mod for my city.

**Comment by Dolu1990** [comment]
Thanks for comment :)
If you have any other issue or improvement to suggest  => do not hesitate to make new issue ^^
Juste, for the moment, the mod is under beta flag. Make often back up of your map ^^ Actualy no issue that crash the map are knowed. but who know ?
