### ISSUE TITLE
Crash with turkish locale.

### ISSUE THREAD

**Issue by jikuja** [Electrical-Age/ElectricalAge#400]
http://pastebin.com/emwEkAeZ

```
java.lang.IllegalArgumentException: No enum constant mods.eln.sixnode.electricalwatch.ElectricalWatchDescriptor.Kind.DİGİTAL
    at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_73]
    at mods.eln.sixnode.electricalwatch.ElectricalWatchDescriptor$Kind.valueOf(ElectricalWatchDescriptor.java:21) ~[ElectricalWatchDescriptor$Kind.class:?]
    at mods.eln.sixnode.electricalwatch.ElectricalWatchDescriptor.<init>(ElectricalWatchDescriptor.java:31) ~[ElectricalWatchDescriptor.class:?]
    at mods.eln.Eln.registerSixNodeMisc(Eln.java:1932) ~[Eln.class:?]
    at mods.eln.Eln.preInit(Eln.java:598) ~[Eln.class:?]
```

Probably caused by bad String.toUpperCase usage. `Note: This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, "title".toUpperCase() in a Turkish locale returns "T\u0130TLE", where '\u0130' is the LATIN CAPITAL LETTER I WITH DOT ABOVE character. To obtain correct results for locale insensitive strings, use toUpperCase(Locale.ENGLISH).`

**Comment by cm0x4D** [comment]
Thanks for the issue, we may have a lot of trouble with toLowerCase() as well...
