### ISSUE TITLE
crash on linux

### ISSUE THREAD

**Issue by jes01965** [Electrical-Age/ElectricalAge#52]
sad to say this about linux, how ever it is really picky when it comes to java.
if you don't mind looking in to this, that would be nice.
thanks

Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: Index: 50, Size: 45
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:206)
    at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:876)
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
    at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:643)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669)

**Comment by Dolu1990** [comment]
Hi, This issue frequant. I try to fix that in next release :)
Thanks for issue

**Comment by Dolu1990** [comment]
could you remember your setup when the bug appear ? mods, modpack, in game case ?
