### ISSUE TITLE
Cast exception in grid pole code

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#553]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/12/16 16:14
Description: Ticking memory connection

java.lang.ClassCastException: mods.eln.node.six.SixNode cannot be cast to mods.eln.node.transparent.TransparentNode
	at mods.eln.gridnode.GridLink.getElementFromCoordinate(GridLink.java:55)
	at mods.eln.gridnode.GridElement.onTryGridConnect(GridElement.java:63)
	at mods.eln.gridnode.GridElement.onBlockActivated(GridElement.java:51)
	at mods.eln.node.transparent.TransparentNode.onBlockActivated(TransparentNode.java:182)
	at mods.eln.node.NodeBlockEntity.onBlockActivated(NodeBlockEntity.java:251)
	at mods.eln.node.NodeBlock.func_149727_a(NodeBlock.java:144)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.eln.gridnode.GridLink.getElementFromCoordinate(GridLink.java:55)
	at mods.eln.gridnode.GridElement.onTryGridConnect(GridElement.java:63)
	at mods.eln.gridnode.GridElement.onBlockActivated(GridElement.java:51)
	at mods.eln.node.transparent.TransparentNode.onBlockActivated(TransparentNode.java:182)
	at mods.eln.node.NodeBlockEntity.onBlockActivated(NodeBlockEntity.java:251)
	at mods.eln.node.NodeBlock.func_149727_a(NodeBlock.java:144)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@66661555
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 131765736 bytes (125 MB) / 393011200 bytes (374 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.13.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Elias'/1811129, l='Nuevo Mundo', x=476,43, y=4,00, z=-819,56]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by metc** [comment]
> UCHIJAAAAAAAAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.13.0.jar)

A string substitution is missing here by the way...
