### ISSUE TITLE
Crash when I take a portable battery with energy from the watch

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#61]
Here you are the crash report, if you need it:

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at mods.eln.sixnode.electricalwatch.ElectricalWatchSlowProcess.process(ElectricalWatchSlowProcess.java:51)
    at mods.eln.sim.Simulator.tick(Simulator.java:455)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_4_Simulator_tick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:520)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669)

**Comment by Dolu1990** [comment]
Thanks for issue : D i investigate that this evening

**Comment by Dolu1990** [comment]
That was a very stupid bug from my part, i fix that soon and release that soon to.
Thanks for your github account creation to report this issue  : D

**Comment by Dolu1990** [comment]
released in BETA-1.7_r24

**Comment by ivangouba** [comment]
Thanks to you! :)
