### ISSUE TITLE
Placed blocks and items disappear on world reload.

### ISSUE THREAD

**Issue by calvin-devogel** [Electrical-Age/ElectricalAge#673]
Using ELN 1.14.1, Forge 1614, and minecraft 1.7.10. Whenever I exit the world and reload, all Electrical Age items that have been placed in the world disappear. My game doesn't crash, but I can't figure out what's causing this.

====

*Admin edit*:

**DO NOT USE 1.14.0 and 1.14.1 on Windows anymore - both probably will break your world.**

**HERE SOME IMPORTANT INFO HOW YOU MIGHT SAVE YOUR MAP:**
For all having this problem, you might eventually be able to restore your world, but you need to manually copy files before starting Minecraft for the next time (using the fixed EA build):

- **If you have this problem, avoid loading the affected saves before you have copied the files!**
- Find the Minecraft save files (location depends platform)
- If there are files with the names electricalAgeWorld0.dat.tmp, electricalAgeWorld1.dat.tmp and * electricalAgeWorld-1.dat.tmp*, create a copy of those in another folder or even better copy the whole folder as a backup.
- Rename the files to electricalAgeWorld0.dat, electricalAgeWorld1.dat and * electricalAgeWorld-1.dat* (Just remove the .tmp suffix). If such files were already there, delete them in order to be able to rename the tmp files.
- Now start Minecraft and load the map. There is a chance that the blocks appear now in your world again.

(Sorry I edited your post, but this is the simplest way to inform everyone having the same issue)

**Comment by Nikolai521** [comment]
Hello friend I am also a user with the same problem I am surprised the new items but loading the world disappears everything a pity I hope that for the next version is solved from today I am talking to them and apparently it is a bug.

**Comment by Baughn** [comment]
1.14 has some new code that should be helpful with this.

Can you set `debug=true` in config/Eln.cfg, restart the server, confirm that blocks are failing to stay and then upload the server logs?

**Comment by HoodedCr0w** [comment]
i got the same problem too.

**Comment by Baughn** [comment]
I can't make this happen locally.

Which is to say, I need the logs. If you're running single-player, that means logs/fml-client-latest.log and logs/latest.log. For a server, logs/fml-server-latest.log and logs/latest.log. You can upload them to pastebin.com, or the host of your choice.

**Comment by Baughn** [comment]
If possible, could you use this build? It should give a bit more detail.

https://madoka.brage.info/baughn/ElectricalAge-dev-23.jar

**Comment by Nikolai521** [comment]
That means you need to know what it says in the files
Fml-client-1.log
And
Latest.log

**Comment by Baughn** [comment]
Okay, here's a thought. Are you guys all on Windows?

-- and no, fml-client-latest.log please.

**Comment by Nikolai521** [comment]
Yes

**Comment by Baughn** [comment]
~~Ok, then I think I know what's going on. Hold on a while, I'll probably have a fix in an hour's time.~~

**Comment by AMIDIBOSS** [comment]
Can we retrive blocks?

**Comment by Nikolai521** [comment]
"Ok, then I think I know what's going on. Hold on a while, I'll probably have a fix in an hour's time."

OK

**Comment by Baughn** [comment]
I still need those logs, folks.

**Comment by calvin-devogel** [comment]
I'm away from my desktop at the moment. I'll attach them as soon as I can.

**Comment by Baughn** [comment]
Anyhow, my guess was wrong. Turns out that Windows does *not* prevent Eln from creating its world data backups. The exception stack trace should be telling, assuming you use the dev build I linked above.

**Comment by J0is** [comment]
I have the same problem. After reloading a save all Eln Blocks are gone.
Edit: I'm on Windows 10, Forge 10.13.4.16.14-1.7.10
[latest.log](https://github.com/Electrical-Age/ElectricalAge/files/794708/latest.txt)

**Comment by Baughn** [comment]
Ok, hopefully it's fixed now.

Can you try this new build: https://madoka.brage.info/baughn/ElectricalAge-dev-24.jar

**Comment by cm0x4D** [comment]
Ok, seems we have isolated the problem. Apparently only Windows users are affected. A fix is on it's way.

**DO NOT USE 1.14.0 and 1.14.1 on Windows anymore** - both probably will break your world.

*THE LESS BAD NEWS*:
For all having this problem, you might eventually be able to restore your world, but you need to manually copy files before starting Minecraft for the next time (using the fixed EA build):

- **If you have this problem, avoid loading the affected saves before you have copied the files!**
- Find the Minecraft save files (location depends platform)
- If there are files with the names *electricalAgeWorld0.dat.tmp*, *electricalAgeWorld1.dat.tmp* and * electricalAgeWorld-1.dat.tmp*, create a copy of those in another folder or even better copy the whole folder as a backup.
- Rename the files to *electricalAgeWorld0.dat*, *electricalAgeWorld1.dat* and * electricalAgeWorld-1.dat* (Just remove the *.tmp* suffix). If such files were already there, delete them in order to be able to rename the tmp files.
- Now start Minecraft and load the map. There is a chance that the blocks appear now in your world again.

**Comment by J0is** [comment]
@Baughn After installing dev-24 ElectricalAge is no longer loading.
StackTrace:
`[22:52:53] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:scanDepInfo:510]: Failed to load dependencies.info from ElectricalAge-dev-24.jar as JSON
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.zip.ZipException: error in opening zip file
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.open(Native Method)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:503)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:497)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:445)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.newInstance(Class.java:438)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[22:52:53] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:52:53] [main/ERROR]: Unable to read the jar file ElectricalAge-dev-24.jar - ignoring`

**Comment by Baughn** [comment]
Wut. ...

That makes absolutely no sense... could you try re-downloading it?

**Comment by J0is** [comment]
Ah yes that fixed it... not sure how that happened

**Comment by Baughn** [comment]
Truncated during download, maybe? Not sure how that would happen... well, I may have pressed 'comment' a bit too fast.

Anyway, is dev-24 any help?

**Comment by J0is** [comment]
Yes blocks/items are loading now. Thank you! 👍

**Comment by Baughn** [comment]
Great!

I'll release 1.14.2 once @cm0x4D has reviewed the PR, and if someone else agrees that it works. For now, anyone who wants to live dangerously can try dev-24. (Please do.)

**Comment by Baughn** [comment]
I found another bug in my code, so we now have https://madoka.brage.info/baughn/ElectricalAge-dev-25.jar.

**Comment by Baughn** [comment]
...well, I'd still like to wait for another confirmation before I close this.

Please try the `dev-25` version. Let me know how it goes.

**Comment by cm0x4D** [comment]
> ...well, I'd still like to wait for another confirmation before I close this.

Probably we leave it open for some days as it has the information how a world could be recovered...

**Comment by bloxgate** [comment]
Perhaps put a disclaimer at the top of the 1.14.2 changelog with instructions on how to recover?

**Comment by Nikolai521** [comment]
Hello I am again I had to leave in order since it gives me lazy translate everything can you tell me if they already fixed it?

**Comment by calvin-devogel** [comment]
Don't know if it's been confirmed, but it looks like dev-25 does work. I reloaded and the items are still in-world.

**Comment by Baughn** [comment]
@cdevogel25 You're the second person to confirm it.

Which is great; looks like we can release 1.14.2 now.

**Comment by Nikolai521** [comment]
OK and probe the dev 25 and until now I do not delete anything I'm almost finishing my house and it goes very.

Good job.

**Comment by Baughn** [comment]
I'm releasing 1.14.2.

I'll keep this issue open for another few days, so it's easier to spot for anyone potentially affected.

**Comment by Nikolai521** [comment]
Okay so far so good
