### ISSUE TITLE
Startup crash with AOBD

### ISSUE THREAD

**Issue by mpevner** [Electrical-Age/ElectricalAge#693]
Using the builds from Safranil, 453 [0] and higher crash on startup with AOBD present.
The pertinent line appears as follows:
```
cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field mods.eln.Eln.maceratorRecipes from class ganymedes01.aobd.recipes.modules.ElectricalAge
```
And the full log is here: https://paste.ee/p/UN7FZ

I've tossed this as an issue on the AOBD repo [1], but thought to also bring it to your attention, as AOBD has not been worked on in some time.

[0] http://ci.safranil.fr/job/ElectricalAge/453/
[1] https://github.com/ganymedes01/Another-One-Bites-the-Dust/issues/129

**Comment by Baughn** [comment]
Can you try removing 'private' from maceratorRecipes?

**Comment by mpevner** [comment]
I adjusted as follows in Eln.java and compiled:
```
RecipesList maceratorRecipes = new RecipesList();
void registerMacerator(int id) {
```
It did not work however.

**Comment by Baughn** [comment]
Ok. I'll make sure it gets fixed before the next release; thanks for telling us.

**Comment by mpevner** [comment]
I gave this another go, explicitly changing every Private RecipesList to Public RecipesList in Eln.java. This seems to work so far, but I can see this as being a rather hacky fix. On a probably related note, I think this breaks NEI. I am investigating further in that regard.

**Comment by mpevner** [comment]
Amendment: This was an issue with the mod NEI Integration, which was using an S instead of a Z. I presume at some point the spelling in this mod changed. A custom compile of NEI Integration later and it is resolved.
...I'm not entirely sure of my reading this, but the issue for NEI appears to be magnetiser/magnetizer. In this matter NEI crashes on attempt to view any recipe.
Error excerpt as follows:
```
java.lang.NoSuchFieldError: magnetiserRecipes
	at tonius.neiintegration.mods.electricalage.RecipeHandlerMagnetizer.getRecipes(RecipeHandlerMagnetizer.java:21)
	at tonius.neiintegration.mods.electricalage.RecipeHandlerElnBase.loadCraftingRecipes(RecipeHandlerElnBase.java:71)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
	at tonius.neiintegration.RecipeHandlerBase.loadCraftingRecipes(RecipeHandlerBase.java:100)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
```

**Comment by mpevner** [comment]
I am roughly aware there are plans for a API to be implemented, but in the interim, would it be reasonable to revert the RecipesList's to public from private?

**Comment by bloxgate** [comment]
The API is near finished at the moment actually. See #652 

Though it'd be on AOBD to update to use it, if they're still doing 1.7.10 releases.

**Comment by mpevner** [comment]
Super awesome! Even if they don't update, the source is visible at least so I can always make my own version (I can't seem to find a license regarding source for AOBD).

**Comment by bloxgate** [comment]
Curse says its All Right's Reserved. https://minecraft.curseforge.com/projects/another-one-bites-the-dust/license

**Comment by mpevner** [comment]
Hopefully by default and not choice. With luck, the author can be reached and this can be worked out.
