### ISSUE TITLE
[1.7.2][ELN r28] Ranodm CME.

### ISSUE THREAD

**Issue by MrGraphic** [Electrical-Age/ElectricalAge#72]
I'm getting randomly CME during gameplay after update to r28:

java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:338)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:344)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:212)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1964)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:917)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by asianboi98** [comment]
You should download Open Eye mod, it'll help you with the crash reports

**Comment by MrGraphic** [comment]
Oh. I'm verry sorry this issue is invlid - not related to ELN at all. I was sure I canceled this.

OpenEye is for inexperienced or lazy ppl, Sometimes can cause even more confusion due to log "castration" :).

**Comment by Dolu1990** [comment]
no problem :)
