### ISSUE TITLE
game crashes when I try to use the powerlines

### ISSUE THREAD

**Issue by enderman803** [Electrical-Age/ElectricalAge#738]
game crashes when I try to connect the "Utility_Pole.name or the Utility_pole_w/transformer.name"
I'm running electrical age version 1.13.0
forge-1.7.10-10.13.4.1614-1.7.10
I can't use electrical age 1.14.2 it crashes when I try running it 
game crash report:
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: java/util/Optional
	at mods.eln.gridnode.GridLink.<init>(GridLink.java:33)
	at mods.eln.gridnode.GridLink.addLink(GridLink.java:78)
	at mods.eln.gridnode.GridElement.onTryGridConnect(GridElement.java:86)
	at mods.eln.gridnode.GridElement.onBlockActivated(GridElement.java:51)
	at mods.eln.node.transparent.TransparentNode.onBlockActivated(TransparentNode.java:182)
	at mods.eln.node.transparent.TransparentNodeElement.ghostBlockActivated(TransparentNodeElement.java:471)
	at mods.eln.ghost.GhostElement.onBlockActivated(GhostElement.java:41)
	at mods.eln.ghost.GhostBlock.func_149727_a(GhostBlock.java:156)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: java.util.Optional

**Comment by bloxgate** [comment]
Hi, it looks like you're not using Java 8. Can you confirm this by giving us your Java version?

**Comment by enderman803** [comment]
I have java version "1.6.0_65"

**Comment by bloxgate** [comment]
Java 8 is a requirement for using this mod, you will need to update. 

Sent from my Windows 10 phone

**Comment by AMIDIBOSS** [comment]
https://www.java.com/download/manual.jsp

**Comment by enderman803** [comment]
thank you for helping me solve my problem. =)
