### ISSUE TITLE
The game broke when I connected the buildcraft pipe to "Electrical Age to other energy exporter (800V)".

### ISSUE THREAD

**Issue by BigfootACA** [Electrical-Age/ElectricalAge#840]
The game broke when I connected the buildcraft pipe to "Electrical Age to other energy exporter (800V)".
`[02:55:12] [Server thread/INFO]: Preparing start region for level 0
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:12] [Server thread/WARN] [BuildCraft]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[02:55:12] [Server thread/WARN] [BuildCraft]: Pipe failed to load from NBT at {0},{1},{2}
[02:55:13] [Server thread/INFO]: Changing view distance to 4, from 10
[02:55:26] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[02:55:26] [Netty IO #1/INFO] [FML]: Client protocol version 2
[02:55:26] [Netty IO #1/INFO] [FML]: Client attempting to join with 17 mods : FML@7.10.99.99,BuildCraft|Silicon@7.1.23,Eln@@VERSION@,BuildCraft|Transport@7.1.23,OpenComputers@1.7.1.1127,Forge@10.13.4.1447,academy-craft@1.0.6,LambdaLib@1.2.3,BuildCraft|Factory@7.1.23,BuildCraft|Core@7.1.23,OpenComputers|Core@1.7.1.1127,BuildCraft|Energy@7.1.23,mcp@9.05,BuildCraft|Builders@7.1.23,LambdaLib|Core@1.2.3,MemoryCleaner@1.0,BuildCraft|Robotics@7.1.23
[02:55:26] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[02:55:26] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[02:55:26] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[02:55:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[02:55:26] [Server thread/INFO]: bigfootaca[local:E:4b062f00] logged in with entity id 331 at (-223.69172154901236, 65.67422952422899, 127.24485690932143)
[02:55:26] [Server thread/INFO]: bigfootaca 加入了游戏
[02:55:26] [ForkJoinPool-1-worker-3/INFO] [OpenComputers]: Starting OpenComputers version check.
[02:55:28] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2336ms behind, skipping 46 tick(s)
[02:55:29] [Client thread/INFO]: [CHAT] §f电力时代 version §61.14.2
[02:55:29] [Client thread/INFO]: [CHAT] > No update available (last stable version)
[02:55:29] [Client thread/INFO]: [CHAT] A new §eOptiFine§f version is available: §eHD Ultra D8§f
[02:55:33] [ForkJoinPool-1-worker-3/INFO] [OpenComputers]: Running the latest OpenComputers version.
[02:56:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraftforge/common/util/ForgeDirection;)Z
    at buildcraft.transport.PipeTransportPower.canPipeConnect(PipeTransportPower.java:121) ~[PipeTransportPower.class:?]
    at buildcraft.transport.Pipe.canPipeConnect(Pipe.java:112) ~[Pipe.class:?]
    at buildcraft.transport.TileGenericPipe.canPipeConnect_internal(TileGenericPipe.java:748) ~[TileGenericPipe.class:?]
    at buildcraft.transport.TileGenericPipe.canPipeConnect(TileGenericPipe.java:771) ~[TileGenericPipe.class:?]
    at buildcraft.transport.TileGenericPipe.computeConnection(TileGenericPipe.java:811) ~[TileGenericPipe.class:?]
    at buildcraft.transport.TileGenericPipe.computeConnections(TileGenericPipe.java:796) ~[TileGenericPipe.class:?]
    at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java:548) ~[TileGenericPipe.class:?]
    at buildcraft.transport.BlockGenericPipe.placePipe(BlockGenericPipe.java:933) ~[BlockGenericPipe.class:?]
    at buildcraft.transport.ItemPipe.func_77648_a(ItemPipe.java:98) ~[ItemPipe.class:?]
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[02:56:15] [Server thread/ERROR]: This crash report has been saved to: /home/bigfoot/./.minecraft/crash-reports/crash-2018-02-12_02.56.14-server.txt
[02:56:15] [Server thread/INFO]: Stopping server
[02:56:15] [Server thread/INFO]: Saving players
[02:56:15] [Server thread/INFO]: Saving worlds
[02:56:15] [Server thread/INFO]: Saving chunks for level '新的世界'/Overworld
[02:56:15] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 18-2-12 上午2:56
Description: Exception in server tick loop

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraftforge/common/util/ForgeDirection;)Z
    at buildcraft.transport.PipeTransportPower.canPipeConnect(PipeTransportPower.java:121)
    at buildcraft.transport.Pipe.canPipeConnect(Pipe.java:112)
    at buildcraft.transport.TileGenericPipe.canPipeConnect_internal(TileGenericPipe.java:748)
    at buildcraft.transport.TileGenericPipe.canPipeConnect(TileGenericPipe.java:771)
    at buildcraft.transport.TileGenericPipe.computeConnection(TileGenericPipe.java:811)
    at buildcraft.transport.TileGenericPipe.computeConnections(TileGenericPipe.java:796)
    at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java:548)
    at buildcraft.transport.BlockGenericPipe.placePipe(BlockGenericPipe.java:933)
    at buildcraft.transport.ItemPipe.func_77648_a(ItemPipe.java:98)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 4.15.2-2-ARCH
    Java Version: 1.8.0_161, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 566976320 bytes (540 MB) / 838860800 bytes (800 MB) up to 2147483648 bytes (2048 MB)
    JVM Flags: 5 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1447 Optifine OptiFine_1.7.10_HD_U_C1 17 mods loaded, 17 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1447-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.4.1447} [Minecraft Forge] (forge-1.7.10-10.13.4.1447-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.7.1.1127} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    academy-craft{1.0.6} [Academy Craft] (AcademyCraft-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MemoryCleaner{1.0} [Memory Cleaner] (MemoryCleaner.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.7.1.1127} [OpenComputers] (OpenComputers-MC1.7.10-1.7.1.1127-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['bigfootaca'/331, l='新的世界', x=-223.61, y=65.30, z=124.75]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
[02:56:15] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:354]: #@!@# Game crashed! Crash report saved to: #@!@# /home/bigfoot/./.minecraft/crash-reports/crash-2018-02-12_02.56.14-server.txt
[02:56:15] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[02:56:15] [Server thread/INFO]: Saving chunks for level '新的世界'/Nether
[02:56:15] [Server thread/INFO]: Saving chunks for level '新的世界'/The End
[02:56:15] [Server thread/INFO] [FML]: Unloading dimension 0
[02:56:15] [Server thread/INFO] [FML]: Unloading dimension -1
[02:56:15] [Server thread/INFO] [FML]: Unloading dimension 1
[02:56:15] [Server thread/INFO] [FML]: Applying holder lookups
[02:56:15] [Server thread/INFO] [FML]: Holder lookups applied
[02:56:15] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[02:56:15] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
[crash-2018-02-12_02.56.14-server.txt](https://github.com/Electrical-Age/ElectricalAge/files/1714747/crash-2018-02-12_02.56.14-server.txt)
`

**Comment by jrddunbr** [comment]
For future reference, logs this long should really be pasted into pasebin and then paste the link here. It's poorly formatted, especially since it's not in a code block, making it even more difficult to read. Parts of this log even think they are one massive link, which makes it difficult to read.

**Comment by cm0x4D** [comment]
Your installation of forge is outdated. Update to forge 10.13.4.1614 or never.

**Comment by BigfootACA** [comment]
[crash-2018-02-12_04.20.54-server.txt](https://github.com/Electrical-Age/ElectricalAge/files/1714805/crash-2018-02-12_04.20.54-server.txt)

**Comment by jrddunbr** [comment]
I've read nothing positive about memory cleaner. I have no idea how it works, and I find it very suspicious. I would get rid of it if I were you.


That aside,
Buildcraft appears to want to have cofh core installed in order to work with Electrical Age. I would go fetch the newest version of [cofh core](https://minecraft.curseforge.com/projects/cofhcore/files/2388750), which also requires the [cofh lib](https://minecraft.curseforge.com/projects/cofh-lib/files/2388747). See if that resolves the problem.

**Comment by jrddunbr** [comment]
I decompiled MemoryCleaner. It's literally just a call to GC at a regular interval, and a config/command structure to increase, decrease, or disable that interval. Instead, you should just configure your java flags correctly and get rid of the mod. This mod will cause more performance decreases than increases, unless you literally don't have enough allocated ram and crash your game.

Since it's mostly only listed on 3rd party websites, the odds of it being malware is pretty good.
