### ISSUE TITLE
crash with projectE

### ISSUE THREAD

**Issue by tonimark** [Electrical-Age/ElectricalAge#842]
so yeah... I put a transmutation table and I insert the tome knowledge to unlock every stuff I type electrical age to filter the electrical age  from other mods and when I get to the 4th page the game freezes for a second and then crashes here the crash log:ava.lang.NullPointerException: 

    at mods.eln.item.BrushDescriptor.getLife(BrushDescriptor.java:48)
    at mods.eln.item.BrushDescriptor.renderItem(BrushDescriptor.java:109)
    at mods.eln.generic.SharedItem.renderItem(SharedItem.java:75)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jrddunbr** [comment]
How recent a version of Electrical Age are you using? I would suggest going to Forge and picking up the most recent version and trying to see if you can replicate it.

**Comment by jrddunbr** [comment]
It looks like it may be caused in an older version by a null pointer exception, referenced in #697. It appears that it was fixed in a later version, and in the development branch, that file has been completely replaced.

**Comment by redstonegenious** [comment]
There is a specific item that the transmission tablet doesn't like. That is the paintbrush. (And EVERY color of it, even the uncolored one) Unlearn it from the tablet and the game should stop crashing.

**Comment by redstonegenious** [comment]
I learned this the hard way when I learned the paintbrush, without the tome of knowledge. and this fixed the issue just fine.

**Comment by jrddunbr** [comment]
Does it happen on newer versions of Electrical Age still?

**Comment by redstonegenious** [comment]
I jad the latese version of ELN when I found it. Not shure about project E, however. the brushes are not hard to craft. And I just place a bunch of them in an alchemical bag; and then I transmute that when I need a brush as they act like an ender chest. (Each color has their own invintory)

**Comment by jrddunbr** [comment]
Hmmmmmm
