### ISSUE TITLE
Crash while using NEI Integration

### ISSUE THREAD

**Issue by jrddunbr** [Electrical-Age/ElectricalAge#849]
Was just standing and suddenly things broke...

[log](https://paste.ee/p/zXha8)

(too big for pastebin - let me know if needed later)

```
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access field mods.eln.Eln.compressorRecipes from class tonius.neiintegration.mods.electricalage.RecipeHandlerCompressor
	at tonius.neiintegration.mods.electricalage.RecipeHandlerCompressor.getRecipes(RecipeHandlerCompressor.java:21) ~[RecipeHandlerCompressor.class:?]
	at tonius.neiintegration.mods.electricalage.RecipeHandlerElnBase.loadCraftingRecipes(RecipeHandlerElnBase.java:71) ~[RecipeHandlerElnBase.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331) ~[TemplateRecipeHandler.class:?]
	at tonius.neiintegration.RecipeHandlerBase.loadCraftingRecipes(RecipeHandlerBase.java:100) ~[RecipeHandlerBase.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466) ~[TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20) ~[GuiCraftingRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23) ~[RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301) ~[bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) ~[bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) ~[bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
	... 17 more
```

**Comment by jrddunbr** [comment]
This bug feels familiar. I think it's actually caused by an NEI mod.

**Comment by jrddunbr** [comment]
https://github.com/Electrical-Age/ElectricalAge/commit/690f135b78aa8c924ddd2940f56c3571b4e90469

Nope, this caused it. Something needs to be public for NEI to work... (not the best, but oh well)

**Comment by jrddunbr** [comment]
My suggestion is to revert some of the changes in that commit, there are 4 things that need to be public I believe (all of the instances of `RecipieList`). Particularly, if we can get a new API jar compiled, we can keep the new spelling of magnetizer rather than the one spelled with an `s`.

**Comment by bloxgate** [comment]
Yes, I remember having that issue while working on my API PR (that needs to be rebased again *sigh*). I believe this issue only occurs in dev versions at present. We've had issues opened for this before.

**Comment by jrddunbr** [comment]
I ended up fixing this at some point in the fork. It can be copied over but I think dev here is done.
