### ISSUE TITLE
RedstoneFlux & CoFHLib Complaining of old API classes being used

### ISSUE THREAD

**Issue by eramsorgr** [Electrical-Age/ElectricalAge#957]
This bug-tracker is for bugs, feature requests and development tracking, not general support. Please see the [support page](https://electrical-age.net/contact/) for support and discussion.

- [X] Bug report
- [ ] Feature request

## Issue description
`RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!`

### Steps to reproduce
- Download CoFHLib and RedstoneFlux with Electrical Age
- Run minecraft
- See crashlogs

### Electrical Age version
1.12.0

### Detailed report
```fix
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.EnergyStorage, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.TileEnergyHandler, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyConnection, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyProvider, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyHandler, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyStorage, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: ElectricalAge-1.12.0.jar
    cofh.api.energy.IEnergyReceiver, loaded from: ElectricalAge-1.12.0.jar


    at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:65)
    at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by bloxgate** [comment]
Hi, the 1.7.10 versions are on the backburner a bit as we prioritize the rewrite for Eln2.

That said, the version of ELN you're using is nearly 4 years old at this point. Could you try updating to a newer version, such as the one [here](https://www.curseforge.com/minecraft/mc-mods/electrical-age/files/2937618)?

**Comment by eramsorgr** [comment]
Hey. I apologize for the late response. I am currently attempting to use ELN in 1.12.2, thus why it's that version, I suppose. I took the latest 1.12.2 release from the [1.12.2 branch](https://github.com/Electrical-Age/ElectricalAge/tree/releases/1.12), I hope..

**Comment by bloxgate** [comment]
Ah, the 1.12.2 version isn't seeing any active development right now. Most of the focus is currently on the 1.15 branch! Sorry for the confusion there!
